// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $api_app from "./routes/api/app.ts";
import * as $api_getoldeMessage from "./routes/api/getoldeMessage.ts";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/api/app.ts": $api_app,
    "./routes/api/getoldeMessage.ts": $api_getoldeMessage,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
